---
- name: VM playbook
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ pc_ip }}"
      nutanix_username: "{{ pc_user }}"
      nutanix_password: "{{ pc_password }}"
      validate_certs: false
  tasks:
  - name: Setting Variables
    set_fact:
        vm_name: ""
        cluster_name: ""
        script_path: ""
        subnet_name: ""
        image_name: ""
        password: ""
        fqdn: ""

  - name: Create Cloud-init Script file
    copy:
      dest: "cloud_init.yml"
      content: |
         #cloud-config
         users:
           - default
           - name: nutanix
             shell: /bin/bash
             homedir: /home/nutanix
             sudo: ['ALL=(ALL) NOPASSWD:ALL']
         chpasswd:
           list: |
              root: "{{ password }}"
              nutanix: "{{ password }}"
           expire: False
         ssh_pwauth: yes
         fqdn: "{{ fqdn }}"

  - name: create Vm
    ntnx_vms:
      state: present
      name: "{{ vm_name }}"
      desc: "built by Ansible AWX playbook"
      categories:
        AppType:
          - "Default"
      cluster:
        name: "{{cluster_name}}"
      networks:
        - is_connected: True
          subnet:
            name: "{{ subnet_name }}"
            # mention cluster only when there are multiple subnets with same name accross clusters
            # and subnet name is set above
            cluster:
              name: "{{cluster_name}}"
      disks:
        - type: "DISK"
          size_gb: 30
          bus: "SATA"
          clone_image:
            name: "{{ image_name }}"
      vcpus: 1
      cores_per_vcpu: 1
      memory_gb: 1
      guest_customization:
        type: "cloud_init"
        script_path: "./cloud_init.yml"
        is_overridable: True
    register: output

  - name: output of vm created
    debug:
      msg: '{{ output }}'
